"""Cochran-formula manual-validation sampling for two detector precision
checks: mock detection and the pytest setup/teardown/setup_and_teardown
lifecycle heuristic.

Mock-*type* (dummy/stub/spy/fake/mock category) classification was
dropped from manual validation entirely (2026-09) -- no longer sampled,
reviewed, or reported anywhere in this pipeline.

Reuses `collection.validation_sampling`'s Cochran sample-size formula and
stratified allocation (`_sample_population()`) rather than reimplementing
either -- see that module's docstring for the exact formula (95%
confidence / 5% margin of error / p=0.5 by default, finite-population-
corrected) and its content-hash-sorted, seed-deterministic sampling
guarantee (same seed always reproduces the same rows, independent of
source-query row order). This module only supplies its own DB queries
(over `fixtures`, not a pipeline CSV) and its own reviewer-facing schema:

    id, source_url, raw_snippet, detected_label, rater_label, notes

A single-rater schema (one column, `rater_label`: TP/FP/Unsure/404),
deliberately simpler than `validation_sampling.py`'s canonical schema --
these two checks are reviewed by one person, not reconciled across two
independent raters, so there's no separate agreed-label step. `notes` is
where the rater records anything worth flagging (an edge case, something
that doesn't fit cleanly into one of the four labels), not just
disagreement commentary. `id` embeds the source dataset and language
(e.g. `A:java:4821`) for reviewer context, even though the schema has no
separate language column.

Population source: `db/a.db` (Dataset A, full) and `db/c.db` (Dataset C,
full -- NOT `db/c_sampled.db`, which is a fixture-count-matched
sample-down built specifically for RQ1-3's A-vs-C paper statistics, not
the broadest available population for a detector-precision check).

Precision-only, matching validation_sampling.py's own convention: these
samples check "is what the detector flagged actually correct" (TP/FP on
already-positive detections), never recall ("did the detector miss any
real instances") -- recall sampling isn't attempted here.

python -m collection.detection_validation_sampling
"""

from __future__ import annotations

import argparse
import csv
import json
import sqlite3
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from typing import Any

from . import paths
from .corpus_utils import _build_github_url
from .logging_utils import configure_logging, get_logger
from .validation_sampling import _sample_population

logger = get_logger(__name__)

DEFAULT_OUTPUT_ROOT = paths.ROOT_DIR / "validation-samples"
DEFAULT_SEED = 42  # same default seed validation_sampling.py uses

CSV_FIELDNAMES = [
    "id",
    "source_url",
    "raw_snippet",
    "detected_label",
    "rater_label",
    "notes",
]

README_TEXT = """# Detector Precision Validation Samples

Two Cochran-sized (95% confidence, 5% margin of error), stratified,
precision-only samples for manual single-rater review, generated by
`python -m collection.detection_validation_sampling`. Reuses
`collection/validation_sampling.py`'s Cochran formula and stratified
allocation -- see that module's docstring for the math.

| File | Population | Stratified by |
|---|---|---|
| `mock-detection/mock_detection_sample.csv` | Fixtures with `num_mocks > 0` (A+C, all 4 languages) | language |
| `pytest-lifecycle/pytest_lifecycle_sample.csv` | Python `pytest_decorator` fixtures classified setup/teardown/setup_and_teardown (A+C) | lifecycle kind |

Mock-type (dummy/stub/spy/fake/mock category) classification was dropped
from manual validation entirely -- not sampled, reviewed, or reported
here anymore.

## Columns

| Column | Meaning |
|---|---|
| `id` | `<dataset>:<language>:<db row id>` -- unique, links back to db/{a,c}.db |
| `source_url` | GitHub blob URL to the fixture's file at its exact commit, line-anchored |
| `raw_snippet` | The code the rater should judge (the fixture body) |
| `detected_label` | What the detector actually assigned |
| `rater_label` | Empty -- filled in by the (single) rater: TP / FP / Unsure / 404 |
| `notes` | Empty -- observations: what was found, edge cases worth a second look, anything that doesn't fit cleanly into one of the four labels |

## Label values

Same convention as `validation-samples/README.md`: **TP** (detection
correct), **FP** (detection wrong), **Unsure** (can't tell from the
evidence shown), **404** (artifact no longer accessible -- excluded from
the precision denominator, not counted as FP).

Precision-only: these samples check whether a positive detection is
correct, not whether the detector missed anything (no recall sampling).

Population: `db/a.db` + `db/c.db` (both full, not `db/c_sampled.db`).
"""


@dataclass(frozen=True)
class SampleResult:
    step: str
    output_file: Path
    population_size: int
    sample_size: int
    strata: list[dict[str, Any]]


def _fetch_mock_detection_rows(conn: sqlite3.Connection, dataset: str) -> list[dict[str, Any]]:
    """One row per fixture with >=1 mock, for the mock-*detection*
    precision check: is `has_mock=True` actually correct for this
    fixture? `raw_snippet` is the fixture's own body (the reviewer needs
    the whole fixture to judge whether it really mocks something, not
    just a matched substring)."""
    rows = conn.execute(
        """
        SELECT f.id, tf.language, r.full_name, f.commit_sha, tf.relative_path,
               f.start_line, f.end_line, f.raw_source, f.num_mocks
        FROM fixtures f
        JOIN test_files tf ON f.file_id = tf.id
        JOIN repositories r ON f.repo_id = r.id
        WHERE f.num_mocks > 0
        """
    ).fetchall()
    return [
        {
            "id": f"{dataset}:{language}:{fixture_id}",
            "language": language,
            "source_url": _build_github_url(
                repo_name, commit_sha or "", relative_path or "", start_line or 0, end_line or 0
            ),
            "raw_snippet": raw_source or "",
            "detected_label": f"has_mock=True (num_mocks={num_mocks})",
        }
        for (
            fixture_id,
            language,
            repo_name,
            commit_sha,
            relative_path,
            start_line,
            end_line,
            raw_source,
            num_mocks,
        ) in rows
    ]


def _fetch_pytest_lifecycle_rows(conn: sqlite3.Connection, dataset: str) -> list[dict[str, Any]]:
    """One row per Python pytest_decorator fixture classified setup/
    teardown/setup_and_teardown, for the lifecycle-heuristic precision
    check (classify_pytest_fixture_kind() in detector_python.py). 'other'
    is excluded -- that classifier only ever returns 'other' when
    raw_source fails to re-parse at all (a data-integrity edge case, not
    a real lifecycle outcome), so it's not one of the three kinds this
    check is validating."""
    rows = conn.execute(
        """
        SELECT f.id, r.full_name, f.commit_sha, tf.relative_path,
               f.start_line, f.end_line, f.raw_source, f.fixture_type_kind
        FROM fixtures f
        JOIN test_files tf ON f.file_id = tf.id
        JOIN repositories r ON f.repo_id = r.id
        WHERE f.fixture_type = 'pytest_decorator'
          AND f.fixture_type_kind IN ('setup', 'teardown', 'setup_and_teardown')
        """
    ).fetchall()
    return [
        {
            "id": f"{dataset}:python:{fixture_id}",
            "lifecycle_kind": fixture_type_kind,
            "source_url": _build_github_url(
                repo_name, commit_sha or "", relative_path or "", start_line or 0, end_line or 0
            ),
            "raw_snippet": raw_source or "",
            "detected_label": fixture_type_kind,
        }
        for (
            fixture_id,
            repo_name,
            commit_sha,
            relative_path,
            start_line,
            end_line,
            raw_source,
            fixture_type_kind,
        ) in rows
    ]


def _write_sample_csv(
    step_dir: Path, filename: str, sampled_rows: list[dict[str, Any]]
) -> Path:
    step_dir.mkdir(parents=True, exist_ok=True)
    out_path = step_dir / filename
    with out_path.open("w", newline="", encoding="utf-8") as fh:
        writer = csv.DictWriter(fh, fieldnames=CSV_FIELDNAMES)
        writer.writeheader()
        for row in sampled_rows:
            writer.writerow(
                {
                    "id": row["id"],
                    "source_url": row["source_url"],
                    "raw_snippet": row["raw_snippet"],
                    "detected_label": row["detected_label"],
                    "rater_label": "",
                    "notes": "",
                }
            )
    return out_path


def _run_one(
    *,
    step: str,
    filename: str,
    rows: list[dict[str, Any]],
    stratify_by: tuple[str, ...],
    confidence_level: float,
    margin_of_error: float,
    proportion: float,
    seed: int,
    output_root: Path,
) -> SampleResult:
    sampled, strata_metadata = _sample_population(
        rows, stratify_by, confidence_level, margin_of_error, proportion, seed
    )
    step_dir = output_root / step
    out_path = _write_sample_csv(step_dir, filename, sampled)
    return SampleResult(
        step=step,
        output_file=out_path,
        population_size=len(rows),
        sample_size=len(sampled),
        strata=strata_metadata,
    )


def run_detection_validation_sampling(
    *,
    db_a: Path,
    db_c: Path,
    confidence_level: float = 0.95,
    margin_of_error: float = 0.05,
    proportion: float = 0.5,
    seed: int = DEFAULT_SEED,
    output_root: Path = DEFAULT_OUTPUT_ROOT,
) -> list[SampleResult]:
    """Generate both samples. Returns one SampleResult per file,
    also written to `<output_root>/<step>/sample_metadata.json`."""
    results: list[SampleResult] = []

    conn_a = sqlite3.connect(db_a)
    conn_c = sqlite3.connect(db_c)
    try:
        mock_detection_rows = _fetch_mock_detection_rows(
            conn_a, "A"
        ) + _fetch_mock_detection_rows(conn_c, "C")
        pytest_lifecycle_rows = _fetch_pytest_lifecycle_rows(
            conn_a, "A"
        ) + _fetch_pytest_lifecycle_rows(conn_c, "C")
    finally:
        conn_a.close()
        conn_c.close()

    results.append(
        _run_one(
            step="mock-detection",
            filename="mock_detection_sample.csv",
            rows=mock_detection_rows,
            stratify_by=("language",),
            confidence_level=confidence_level,
            margin_of_error=margin_of_error,
            proportion=proportion,
            seed=seed,
            output_root=output_root,
        )
    )
    results.append(
        _run_one(
            step="pytest-lifecycle",
            filename="pytest_lifecycle_sample.csv",
            rows=pytest_lifecycle_rows,
            stratify_by=("lifecycle_kind",),
            confidence_level=confidence_level,
            margin_of_error=margin_of_error,
            proportion=proportion,
            seed=seed,
            output_root=output_root,
        )
    )

    metadata = {
        "confidence_level": confidence_level,
        "margin_of_error": margin_of_error,
        "proportion": proportion,
        "seed": seed,
        "timestamp": datetime.now().strftime("%Y%m%d_%H%M%S"),
        "results": [
            {
                "step": r.step,
                "output_file": str(r.output_file),
                "population_size": r.population_size,
                "sample_size": r.sample_size,
                "strata": r.strata,
            }
            for r in results
        ],
    }
    output_root.mkdir(parents=True, exist_ok=True)
    (output_root / "sample_metadata_detection_validation.json").write_text(
        json.dumps(metadata, indent=2), encoding="utf-8"
    )
    (output_root / "README_detection_validation.md").write_text(README_TEXT, encoding="utf-8")

    for r in results:
        logger.info(
            "[Detection Validation Sampling] %s: N=%d -> n=%d -> %s",
            r.step,
            r.population_size,
            r.sample_size,
            r.output_file,
        )

    return results


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description=(
            "Draw Cochran-sized manual-validation samples for mock "
            "detection and the pytest setup/teardown lifecycle heuristic."
        )
    )
    parser.add_argument("--db-a", type=Path, default=paths.db_path("a"))
    parser.add_argument("--db-c", type=Path, default=paths.db_path("c"))
    parser.add_argument("--confidence-level", type=float, default=0.95)
    parser.add_argument("--margin-error", type=float, default=0.05)
    parser.add_argument("--proportion", type=float, default=0.5)
    parser.add_argument("--seed", type=int, default=DEFAULT_SEED)
    parser.add_argument("--output-root", type=Path, default=DEFAULT_OUTPUT_ROOT)
    return parser


def main(argv: list[str] | None = None) -> int:
    configure_logging(fmt="%(message)s")
    args = build_parser().parse_args(argv)
    run_detection_validation_sampling(
        db_a=args.db_a,
        db_c=args.db_c,
        confidence_level=args.confidence_level,
        margin_of_error=args.margin_error,
        proportion=args.proportion,
        seed=args.seed,
        output_root=args.output_root,
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
